cloud:
  db-host: localhost
  eureka-host: localhost
  currency-url: http://localhost:8081


spring:
  application:
    name: exchange-precessing-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${cloud.db-host}:5432/processing
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db
    url: jdbc:postgresql://${cloud.db-host}:5432/processing
    user: postgres
    password: postgres

  security:
    oauth2:
      resourceserver:
        opaque:
          introspection-uri: http://localhost:9000/oauth2/token-info
          introspection-client-id: processing
          introspection-client-secret: processing123

server:
  port: 8082




service:
  currency:
    url: ${cloud.currency-url}


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${cloud.eureka-host}:8761/eureka


